<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <Version>1.14.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entitas/version.txt" />
    <EmbeddedResource Include="version.txt">
      <LogicalName>version.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\devs\DesperateDevs.Caching\DesperateDevs.Caching.csproj" />
    <ProjectReference Include="..\..\devs\DesperateDevs.Reflection\DesperateDevs.Reflection.csproj" />
  </ItemGroup>

</Project>
