<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DesperateDevs.Extensions/DesperateDevs.Extensions.csproj" />
    <ProjectReference Include="..\..\sherlog\Sherlog\Sherlog.csproj" />
  </ItemGroup>

</Project>
